### ISSUE TITLE
Bandcamp provider missing on compiled plugin

### ISSUE THREAD

**Issue by maniqui** [NicolasGraph/oui_player#1]
It seems that Bandcamp has been left out from the compiled plugin (and the manifest.json). 

PS: thanks for the plugin, I'm starting to tinker with it.

**Comment by NicolasGraph** [comment]
@maniqui; Bandcamp is not supported for now. I need to take a look at it again to remember where was the problem.

**Comment by NicolasGraph** [comment]
@maniqui, the problem with Bandcamp is that it is not possible, as far as I know, to get the album or track ID which is needed to embed the player from an URL. I could (should?) support Bandcamp with `<txp:oui_player provider="Bandcamp" play="2926741326" />` (and add a way to provide the track ID) but I can't get `<txp:oui_player play="https://leffondras.bandcamp.com/album/les-flavescences-lp" />` work. The conditional tag seems also useless for this case.

**Edit:** Otherwise I could do something from the player URL, with something like `https://bandcamp.com/EmbeddedPlayer/album=2926741326/track=3574641674`. Not easy to get for the user but it would work…

**Edit:** We also need a way to tell the plugin what kind of ID is provided when using `<txp:oui_player provider="Bandcamp" play="2926741326" />`. Is that an album or a track? I would like to keep something as generic as possible.

**Comment by maniqui** [comment]
Yes, it seems Bandcamp doesn't have any kind of API to get the album or track ID. 

I wonder if scraping the website (using the album URL) is a viable option. Problem is that if each time the plugin is called (for Bandcamp being the embed provider) you have to scrap the website, it could make things really slow. 
Anyway, I think the way to go is by looking at the embed code (or directly the page source) provided by Bandcamp and manually copy-pasting the album or track ID. And manually specifying if it's a track or an album (via an extra attribute or maybe just prepending a character before the ID, like `t123456` or `a123456`).

**Comment by NicolasGraph** [comment]
> Yes, it seems Bandcamp doesn't have any kind of API to get the album or track ID.
I wonder if scraping the website (using the album URL) is a viable option.

The way the plugin work avoid any external query to get ID's or embed codes, so I don't want to scrap the Bandcamp code.

> And manually specifying if it's a track or an album (via an extra attribute or maybe just prepending a character before the ID, like t123456 or a123456).

I wouldn't like to add an extra attribute because it would break the plugin logic. I would like to keep the plugin easily work with a single custom field where to put the ID/URL to play.

You are right about finding a way to specify the type of ID in the `play` attribute.
Twitch already accepts channels or videos ID's, however, the way this provider manage ID's is easier to use (natively prepending a `v` before videos ID's).

For Bandcamp we need to accept an album ID, a track ID or both at the same time. And as there is no way to differenciate them, we need something else like prefixes or any other system. 

From the dev point of view, the more consistent way to do would be to use something like `play="album=123456/track=123456"`, directly using what the the player need. Your idea could work too with some extra work and I also thought about `play="123456:123456"`, keeping the colon as the first character if it's only a track ID.

…Now we mainly need a way to potentially manage two ID's in the code, which is not supported for now. It's doable but I'm not sure to do it promptly.

**Comment by maniqui** [comment]
What's the use case for having the track ID and album ID at the same time? I can't recall that kind of embed in Bandcamp, and how is it presented to the user. Unless the idea is to embed an album with a pre-selected track on the list to play. In that case, it makes sense.

I vote for `play="album=123456/track=123456"`. It's the more explicit one ("better explicit than implicit") and it can be copy-pasted directly from the Bandcamp source page (or the embed code).

**Comment by NicolasGraph** [comment]
As far as I tried, If you use a track ID only, the main player title is the track title linked to the track related Bandcamp page. If you use an album ID also, the main title is the album title link to the related page and the track title is just above the player progress bar. Both play the provided track.

> I vote for `play="album=123456/track=123456".`

The plugin still needs some work, I'll think about it, thanks.
